### ISSUE TITLE
Plan CIC intro to computing classes

### ISSUE THREAD

**Issue by pipitone** [CoBrALab/admin#12]
Ideas:
- What is a computer / Ask us anything (e.g. What is a "core"? What is RAM?)
- Linux / Terminal 
- Navigating files/filesystem (ls, cp, mv, mkdir, ln, nano)
- Intro to shell scripting
- Intro to version control / github

See software carpentry and http://tigrlab.github.com/computing.skills for inspiration

**Comment by pipitone** [comment]
The CIC Educational Series will be starting next week. 

The first two sessions will be on Thursday, Sept 11, 2014 (1-3pm) and Friday, Sept 12, 2014 (10-12am). Each session will be two hours long. 

The first session will be a gentle introduction to computers and Linux. This session is geared towards people who have limited or no experience with Linux and are/will be using it for data processing or analysis tasks. We will cover the following topics: 
- Your questions: What is X? (e.g. What /is/ a computer? What is a hard drive? A core? etc..) Ask us anything. 
- What is that black screen with tiny letters I see people staring at? (i.e. the Terminal)
- Files and directories/folders
- Working with files and folders (creating, deleting, editing, copying, moving, etc..)

The second session will continue the introduction to the terminal, and cover the topics: 
- Remembering what you've done (history)
- Automating repetitive tasks (for/while loops)
- Accessing a computer remotely (ssh)

Space is limited, sign up for these classes here: 
- [Gentle Intro to Computers - Thu, Sept 11, 2014 1-3pm @ CIC](https://www.eventbrite.ca/e/cic-educational-series-gentle-introduction-to-computers-tickets-12962062879)
- [Intro to the terminal - Fri, Sept 12, 2014 - 10-12pm @ CIC](https://www.eventbrite.ca/e/cic-educational-series-introduction-to-linux-terminal-tickets-12962145125)

Note: you will need to bring a laptop to these sessions.

**Comment by gdevenyi** [comment]
http://datasci.kitzes.com/lessons/python/reproducible_workflow.html

**Comment by pipitone** [comment]
- Introduce ourselves (name, role, research, but terse!)
- Review file system, `cd`, `ls`, `cp`, `rm`, `mkdir`
- `history` (and perhaps `ctrl-r`)
- Globbing (and `echo`) using `*.mnc`, `{1..10}`, to do things on multiple files (i.e. mv, rename)
- For loops
- SSH/SCP (and maybe rsync)
