### ISSUE TITLE
Test quarantine software on workstations and compute node

### ISSUE THREAD

**Issue by gdevenyi** [CoBrALab/admin#3]

**Comment by pipitone** [comment]
I've tried building the minc-toolkit on `ciccs08` in `/opt/quarantine/minc-toolkit/1.0.01-test`. The build is _almost_ complete, but `mincresample` tests fail during the build (segfault, in fact) and I'm not sure why.

**Comment by pipitone** [comment]
I should note that none of the other quarantine modules have been compiled yet on the compute servers.

**Comment by gdevenyi** [comment]
mincresample bug that somehow doesn't crash newer compilers. Adding patch

https://github.com/BIC-MNI/minc-toolkit/issues/9

**Comment by gdevenyi** [comment]
Patch successful, build proceeds

**Comment by gdevenyi** [comment]
Fixed ITK problem by forking the ITK source and patching cmake-modules
