### ISSUE TITLE
test nfsv4 solution of removing mdns4

### ISSUE THREAD

**Issue by gdevenyi** [CoBrALab/admin#33]

**Comment by gdevenyi** [comment]
https://bugs.launchpad.net/ubuntu/+source/nfs-utils/+bug/1270445

**Comment by gdevenyi** [comment]
Fixed half the problem, the other half being learning how nfs4 works, exports are at / not /exports.

Need to transition /data and /opt/quarantine to nfs4

**Comment by gdevenyi** [comment]
Works!

**Comment by pipitone** [comment]
Just a note, I found on 10.04 removing `mdns` from `nsswitch.conf` did nothing. I had to black list the `rpcsec_gss_krb5`module.
