### ISSUE TITLE
Create a page on the cobralab.ca website for digital atlases

### ISSUE THREAD

**Issue by pipitone** [CoBrALab/admin#34]
Perhaps http://cobralab.ca/digital-atlases

Atlases to include: 
- Hippocampus 
- Cerebellum
- Sub-cortical
- Thalamic subdivisions

**Comment by gdevenyi** [comment]
Atlases left

Mallar/Matt needs to provide
- Sub-cortical
- Thalamic subdivisions

Gabriel needs to re-write like members page
http://jekyllrb.com/docs/posts/

**Comment by gdevenyi** [comment]
Mallar suggests
-  striatal subdivision

**Comment by gdevenyi** [comment]
/scratch/m/mchakrav/mpark/Atlases_collab/colin has the stuff- including:

labels_striatum.mnc: striatal subdivisions
labels_subcort.mnc: subcortical structures
labels_thalamus_cyto.mnc: thalamic subregions

**Comment by pipitone** [comment]
I've put the amygdala, cerebellum, hippocampus, and colin27-based subcortical atlases (labels and surfaces) into http://github.com/cobralab/atlases. The cerebellum, hippocampus and colin27 atlases are now stubbed out on http://cobralab.ca/digital-atlases. I'm closing this issue since the basics are done.
