### ISSUE TITLE
"Display" while logged in to another machine

### ISSUE THREAD

**Issue by raihaan** [CoBrALab/admin#47]
Trouble using the "Display" function after ssh into another machine (experienced with cicws27 and cicws28 so far, have not tested others)

Despite minc-toolkit being loaded, 
patrai@cicws28:/data/chamal/projects/raihaan/defaced$ module list
Currently Loaded Modulefiles:
  1) quarantine            2) minc-toolkit/1.0.01
patrai@cicws28:/data/chamal/projects/raihaan/defaced$ Display 001_time1_defaced.mnc 
freeglut (no_program_name): failed to open display ''

Other minc functions seem to be operational though when I log into anther machine, ran a mincresample and it operated as usual

**Comment by 7jw9** [comment]
Hey, are you using the visual (-X) option on ssh? ie. ssh -X raihaan@machine

**Comment by raihaan** [comment]
I was not. This fixed it. thanks.
