### ISSUE TITLE
nautilus 

### ISSUE THREAD

**Issue by raihaan** [CoBrALab/admin#48]
Would it be possible to get the nautilus file manager installed? Unless we already have an equivalent that I don't know about?

**Comment by gdevenyi** [comment]
Accessories -> File Manager is not sufficient?

## 

Gabriel A. Devenyi B.Eng. Ph.D.
Research Computing Associate
Computational Brain Anatomy Laboratory
Cerebral Imaging Center
Douglas Mental Health University Institute
McGill University
t: 514.761.6131x4781
e: gdevenyi@gmail.com

**Comment by gdevenyi** [comment]
xdg-open <file or directory>

Will launch the default viewer, including pcfileman
