### ISSUE TITLE
Potential new software for lab

### ISSUE THREAD

**Issue by gdevenyi** [CoBrALab/admin#51]
Logging software I come across while reading

**Comment by gdevenyi** [comment]
https://stnava.github.io/ANTs/

**Comment by gdevenyi** [comment]
https://jeffduda.github.io/NeuroBattery/

**Comment by pipitone** [comment]
> https://stnava.github.io/ANTs/

.. is what mincANTS is, just without the ITK additions to allow it to
read/write minc files. mincANTS is part of minc-toolkit.

**Comment by gdevenyi** [comment]
It looks like ANTs has moved forwards compared to mincANTs, just wondering if improvements could be backported.
