### ISSUE TITLE
Setup ansible for workstations

### ISSUE THREAD

**Issue by pipitone** [CoBrALab/admin#7]

**Comment by gdevenyi** [comment]
Hosts files complete

**Comment by gdevenyi** [comment]
Workstation software complete

**Comment by gdevenyi** [comment]
Remaining:
Autofs
Static Mounts
NIS
Gridengine
Quarantine (/etc/profile.d)

**Comment by gdevenyi** [comment]
Remaining
- [x] Grid engine
- [x] uBlock chrome autoload
- [x] Adblock Plus autoload
- [ ] setup printers

**Comment by gdevenyi** [comment]
Issue too general, see other ansible issues
